name: 'markdown-translation'
description: 'extract xliff and skeleton from markdown and compose markdown from them'
author: 'moki'
inputs:
  allowed-associations:
    description: Array of allowed associations for actors
    default: '["OWNER"]'
  github-token:
    description: github token
    required: true
  post-usage:
    description: 'if usage information should be posted upod pull_request creation, specify "true" or "false"'
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: file-text
  color: gray-dark
