name: 'markdown-translation-issue-comments'
on:
  issue_comment:
    types: [created, edited]
jobs:
  test:
    permissions:
      pull-requests: write
      contents: write
      packages: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: parse markdown-translation command from comments
        id: parameters-parsing
        uses: actions-ecosystem/action-regex-match@v2.0.2
        with:
          text: ${{github.event.comment.body}}
          regex: '^markdown-translation:\s*(extract|compose)\s+([\w\d-]+)\s+([\w\d-]+)\s+([\w]+\-[\w]+)\s+([\w]+\-[\w]+)(?=\s|$)'
      - name: check command parsing
        id: parameters-parsing-status
        run: echo -e "status=${{steps.parameters-parsing.outputs.group1 != '' && steps.parameters-parsing.outputs.group2 != '' && steps.parameters-parsing.outputs.group3 != '' && steps.parameters-parsing.outputs.group4 != '' && steps.parameters-parsing.outputs.group5 != ''}}" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/checkout@v4
        if: ${{steps.parameters-parsing-status.outputs.status == 'true'}}
      - name: markdown-translation
        if: ${{steps.parameters-parsing-status.outputs.status == 'true'}}
        uses: ./
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          pr: ${{steps.parameters-parsing.outputs.pr}}
          command: ${{steps.parameters-parsing.outputs.command}}
          input: ${{steps.parameters-parsing.outputs.input}}
          output: ${{steps.parameters-parsing.outputs.output}}
          sll: ${{steps.parameters-parsing.outputs.sll}}
          tll: ${{steps.parameters-parsing.outputs.tll}}
          git_name: ${{steps.parameters-parsing.outputs.git_name}}
          git_email: ${{steps.parameters-parsing.outputs.git_email}}
          extract_message: ${{steps.parameters-parsing.outputs.extract_message}}
          compose_message: ${{steps.parameters-parsing.outputs.compose_message}}
