name: 'markdown-translation-issue-comments'
on:
  issue_comment:
    types: [created, edited]
jobs:
  test:
    permissions:
      pull-requests: write
      contents: write
      packages: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: parse markdown-translation parameters from comment
        id: parameters-parsing
        uses: actions-ecosystem/action-regex-match@v2.0.2
        with:
          text: ${{github.event.comment.body}}
          regex: '^markdown-translation:\s*(extract|compose)\s+([\w\d-]+)\s+([\w\d-]+)\s+([\w]+\-[\w]+)\s+([\w]+\-[\w]+)(?=\s|$)'
      - name: parameters parsing status
        id: parameters-parsing-status
        run: echo -e "status=${{steps.parameters-parsing.outputs.group1 != '' && steps.parameters-parsing.outputs.group2 != '' && steps.parameters-parsing.outputs.group3 != '' && steps.parameters-parsing.outputs.group4 != '' && steps.parameters-parsing.outputs.group5 != ''}}" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/checkout@v4
        if: ${{steps.parameters-parsing-status.outputs.status == 'true'}}
      - name: markdown-translation
        if: ${{steps.parameters-parsing-status.outputs.status == 'true'}}
        uses: ./
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          pr: ${{github.event.issue.number}}
          command: ${{steps.parameters-parsing.outputs.group1}}
          input: ${{steps.parameters-parsing.outputs.group2}}
          output: ${{steps.parameters-parsing.outputs.group3}}
          sll: ${{steps.parameters-parsing.outputs.group4}}
          tll: ${{steps.parameters-parsing.outputs.group5}}