name: 'markdown-translation-usage'
on:
  workflow_dispatch:
    inputs:
      pr:
        description: pull request to checkout
        required: true
      command:
        description: 'xliff command to run, acceptable values: extract or compose'
        required: true
      input:
        description: input folder
        required: true
      output:
        description: output folder
        required: true
      sll:
        description: 'source language locale, example: ru-RU'
        default: 'ru-RU'
        required: true
      tll:
        description: 'target language locale, example: en-US'
        default: 'en-US'
        required: true
      extract_mesage:
        description: git message to use to commit extract results
        default: 'markdown-translation: extract xliff'
      compose_mesage:
        description: git message to use to commit compose results
        default: 'markdown-translation: compose xliff into translated markdown'
jobs:
  test:
    permissions:
      pull-requests: write
      contents: write
      packages: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          pr: ${{github.event.inputs.pr}}
          command: ${{github.event.command}}
          input: ${{github.event.inputs.input}}
          output: ${{github.event.inputs.output}}
          sll: ${{github.event.inputs.sll}}
          tll: ${{github.event.inputs.tll}}
